# Generated by Django 4.2.3 on 2023-08-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hymnbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arranger',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'arranger', 'verbose_name_plural': 'arrangers'},
        ),
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name': 'audio file', 'verbose_name_plural': 'audio files'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'bookmark', 'verbose_name_plural': 'bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='hymn',
            options={'ordering': ['title'], 'verbose_name': 'hymn', 'verbose_name_plural': 'hymns'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title'], 'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterModelOptions(
            name='transcriber',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'transcriber', 'verbose_name_plural': 'transcribers'},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'translator', 'verbose_name_plural': 'translators'},
        ),
        migrations.AlterField(
            model_name='arranger',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='arranger',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(help_text='Audio file', upload_to='hymnbook/audio-files/', verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='voice_type',
            field=models.CharField(choices=[('S0', 'Soprano'), ('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('A0', 'Alto'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('T0', 'Tenor'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B0', 'Bajo'), ('B1', 'Bajo 1'), ('B2', 'Bajo 2'), ('I0', 'Solista'), ('I1', 'Solista 1'), ('I2', 'Solista 2'), ('EV', 'SATB')], default='S0', help_text='Type of voice', max_length=2, verbose_name='voice type'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='arrangers',
            field=models.ManyToManyField(blank=True, help_text='Hymn arrangers', related_name='hymns', to='hymnbook.arranger', verbose_name='arrangers'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Hymn authors', related_name='hymns', to='hymnbook.author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='language',
            field=models.ForeignKey(help_text='Hymn language', on_delete=django.db.models.deletion.PROTECT, related_name='hymns', to='hymnbook.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='notes',
            field=models.TextField(blank=True, help_text='Hymn notes', null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='pdf_file',
            field=models.FileField(help_text='Hymn pdf file', upload_to='hymnbook/pdf-files/', verbose_name='pdf file'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='release_date',
            field=models.DateField(help_text='Hymn release date', verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='title',
            field=models.CharField(help_text='Hymn title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='topics',
            field=models.ManyToManyField(help_text='Hymn topics', related_name='hymns', to='hymnbook.topic', verbose_name='topics'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='transcribers',
            field=models.ManyToManyField(blank=True, help_text='Hymn transcribers', related_name='hymns', to='hymnbook.transcriber', verbose_name='transcribers'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='translators',
            field=models.ManyToManyField(blank=True, help_text='Hymn translators', related_name='hymns', to='hymnbook.translator', verbose_name='traslators'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, help_text='Language name', max_length=255, null=True, verbose_name='language name'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, help_text='Topic title', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='transcriber',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='transcriber',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=255, verbose_name='last name'),
        ),
    ]
