# Generated by Django 4.2.3 on 2023-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslide',
            options={'verbose_name': 'carousel slide', 'verbose_name_plural': 'carousel slides'},
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='background_image_file',
            field=models.ImageField(default='default.jpg', help_text='Carousel slide background image', upload_to='images/slides_images/', verbose_name='slide background image'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='text',
            field=models.TextField(help_text='Carousel slide description', verbose_name='slide description'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(help_text='Carousel slide title', max_length=100, verbose_name='slide title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='The user is verified.', verbose_name='verified'),
        ),
    ]
