# Generated by Django 4.2.3 on 2023-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_church_city_alter_church_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='voice_type',
            field=models.CharField(choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bajo 1'), ('B2', 'Bajo 2')], default='S1', max_length=2, verbose_name='voice type'),
        ),
    ]
